version: 2.1
orbs:
  ruby: circleci/ruby@2.4.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-stretch-node
    executor: default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
workflows:
   version: 2.1
   build:
     jobs:
       - build
